question_data = [
    {"question": "A slug's blood is green.", "answer": "True"},
    {"question": "The loudest animal is the African Elephant.", "answer": "False"},
    {
        "question": "Approximately one quarter of human bones are in the feet.",
        "answer": "True",
    },
    {
        "question": "The total surface area of a human lungs is the size of a football pitch.",
        "answer": "True",
    },
    {
        "question": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.",
        "answer": "True",
    },
    {
        "question": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
        "answer": "False",
    },
    {"question": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"question": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"question": "Google was originally called 'Backrub'.", "answer": "True"},
    {"question": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {
        "question": "No piece of square dry paper can be folded in half more than 7 times.",
        "answer": "False",
    },
    {"question": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
]


movie_question = [
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
        "answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "The film '2001: A Space Odyssey' was released on December 31st, 2000.",
        "answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "Shaquille O'Neal appeared in the 1997 film 'Space Jam'.",
        "answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "Samuel L. Jackson had the words, 'Bad Motherf*cker' in-scripted on his lightsaber during the filming of Star Wars.",
        "answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "In Alfred Hitchcock's film 'Psycho' it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
        "answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "In the original script of 'The Matrix', the machines used humans as additional computing power instead of batteries.",
        "answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "'Foodfight!' earned less than $80,000 at box office.",
        "answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "The movie 'The Nightmare before Christmas' was all done with physical objects.",
        "answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
        "answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.",
        "answer": "True",
        "incorrect_answers": ["False"],
    },
]


computer_question = [
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "'HTML' stands for Hypertext Markup Language.",
        "answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "The programming language 'Python' is based off a modified version of 'JavaScript'.",
        "answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "RAM stands for Random Access Memory.",
        "answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
        "answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "The Windows ME operating system was released in the year 2000.",
        "answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "The logo for Snapchat is a Bell.",
        "answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "Linux was first created as an alternative to Windows XP.",
        "answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "Time on Computers is measured via the EPOX System.",
        "answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "The Python programming language gets its name from the British comedy group 'Monty Python.'",
        "answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "Ada Lovelace is often considered the first computer programmer.",
        "answer": "True",
        "incorrect_answers": ["False"],
    },
]

gk_question = [
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "The Lego Group was founded in 1932.",
        "answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
        "answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "The National Animal of Scotland is the Unicorn.",
        "answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "The Great Wall of China is visible from the moon.",
        "answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "Bulls are attracted to the color red.",
        "answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
        "answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "The mitochondria is the powerhouse of the cell.",
        "answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "Pluto is a planet.",
        "answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "The color orange is named after the fruit.",
        "answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "Vietnam's national flag is a red star in front of a yellow background.",
        "answer": "False",
        "incorrect_answers": ["True"],
    },
]

music_qn =[
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Entertainment: Music",
            "question": "Korean girl group, TWICE, consists of 9 members",
            "answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Entertainment: Music",
            "question": "Scatman John's real name was John Paul Larkin.",
            "answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Entertainment: Music",
            "question": "American rapper Dr. Dre actually has a Ph.D. doctorate.",
            "answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Entertainment: Music",
            "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
            "answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Entertainment: Music",
            "question": "A Saxophone is a brass instrument.",
            "answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Entertainment: Music",
            "question": "Michael Jackson wrote The Simpsons song 'Do the Bartman';.",
            "answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Entertainment: Music",
            "question": "The music video to The Buggle's 'Video Killed the Radio Star' was the first music video to broadcast on MTV.",
            "answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Entertainment: Music",
            "question": "Muse is a British (English) rock band",
            "answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Entertainment: Music",
            "question": "The alternative rock band, They Might Be Giants, released their album 'Flood' in 1990. ",
            "answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Entertainment: Music",
            "question": "John Williams composed the music for 'Star Wars'.",
            "answer": "True",
            "incorrect_answers": ["False"],
        },
    ]